# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 95e1b6cac22afe112300b38ed478eb412acf14b3ef861972175a70cbc04edf125352bd7cf8e9d0370bbcfdb2f20045c521df29166350589b4290cd77b0821e80

test:
  secret_key_base: 16a5841e16424531e41e368a7d351f6afb3b34c8f3310178ee722b40f62c04694c18a0a5ae27a2ef87736abc400b937f13d3181fff6880a261e2c1eb7d47d336

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
